package io.linewise.jobfm

/* =============================================================================
 * TIER 2 — PRODUCTION safeAdd PRIMITIVE (the production side of the trusted pair).
 *
 * This is a HAND-WRITTEN shell file, NOT generated by the transpiler. It mirrors
 * the SPEC of the verify side (verify/stainless-lib/SafeArith.scala) with a
 * DIFFERENT implementation, and the two are TRUSTED-EQUIVALENT:
 *
 *   spec  (verify side):  sum in unbounded BigInt; Right(wrapped) iff the sum is
 *                         in the machine range, else Left(Overflow).
 *   impl  (this file):    Math.addExact(a, b); Right(result) on success, and the
 *                         JVM ArithmeticException it throws on overflow caught
 *                         and turned into Left(Overflow).
 *
 * Math.addExact returns the exact sum iff it fits in the machine type and throws
 * ArithmeticException otherwise. That is the SAME boundary the BigInt range check
 * encodes in the spec, so the observable Either is identical: same Right/Left
 * partition over all inputs. The spec's range check is the proof-level statement
 * of what Math.addExact does at runtime — we TRUST this small equivalence rather
 * than proving the JVM intrinsic.
 *
 * Because the implementations differ on purpose, the transpiler does NOT
 * translate safeAdd's definition. Only CALL-SITES of safeAdd pass through the
 * transpiler untouched and resolve against THIS production extension.
 * ========================================================================== */

/** The arithmetic-error ADT — same shape as the verify side. */
sealed trait ArithError
object ArithError:
  case object Overflow extends ArithError

object SafeArith:

  extension (a: Long)
    /** Add two Longs, returning Left(Overflow) instead of wrapping silently.
      * Trusted-equivalent to the verify-side BigInt range check. */
    def safeAdd(b: Long): Either[ArithError, Long] =
      try Right(Math.addExact(a, b))
      catch case _: ArithmeticException => Left(ArithError.Overflow)

  extension (a: Int)
    /** Int variant — same trusted-equivalence against Math.addExact(Int, Int). */
    def safeAddI(b: Int): Either[ArithError, Int] =
      try Right(Math.addExact(a, b))
      catch case _: ArithmeticException => Left(ArithError.Overflow)
