package io.linewise.ledger

import java.sql.Connection
import javax.sql.DataSource

import com.zaxxer.hikari.{HikariConfig, HikariDataSource}
import org.postgresql.ds.PGSimpleDataSource

/* =============================================================================
 * PostgreSQL schema + datasource helpers for the ledger microservice. The schema now
 * carries an explicit account catalog, immutable payout-intent / provider-event /
 * reconciliation tables for recipient-pays-fee flows, and a true multi-entry ledger
 * storage shape (header + numbered entry legs) with DB-enforced conservation.
 * ========================================================================== */
object Jdbc:

  private val defaultUser = "postgres"
  private val defaultPassword = "postgres"
  private val schemaPattern = "[A-Za-z_][A-Za-z0-9_]*".r

  private def pg(url: String, user: String, password: String): PGSimpleDataSource =
    val ds = PGSimpleDataSource()
    ds.setURL(url)
    ds.setUser(user)
    ds.setPassword(password)
    ds

  private def requireSafeSchema(schema: String): Unit =
    require(schemaPattern.matches(schema), s"unsafe PostgreSQL schema name: $schema")

  private def pool(url: String, user: String, password: String, schema: Option[String]): HikariDataSource =
    val cfg = HikariConfig()
    cfg.setJdbcUrl(url)
    cfg.setUsername(user)
    cfg.setPassword(password)
    cfg.setMaximumPoolSize(sys.env.get("LEDGER_DB_POOL_SIZE").flatMap(_.toIntOption).getOrElse(8))
    cfg.setMinimumIdle(0)
    schema.foreach(s => cfg.setPoolName(s"ledger-$s"))
    schema.foreach(cfg.setSchema)
    HikariDataSource(cfg)

  def dataSource(jdbcUrl: String, user: String, password: String): DataSource =
    pool(jdbcUrl, user, password, None)

  def dataSource(jdbcUrl: String, user: String, password: String, schema: String): DataSource =
    requireSafeSchema(schema)
    val admin = pg(jdbcUrl, user, password)
    val c0 = admin.getConnection()
    try
      val st = c0.createStatement()
      try st.execute(s"CREATE SCHEMA IF NOT EXISTS $schema")
      finally st.close()
    finally c0.close()
    pool(jdbcUrl, user, password, Some(schema))

  def dataSource(databaseName: String): DataSource =
    val env = sys.env
    val url = env.getOrElse("LEDGER_JDBC_URL", s"jdbc:postgresql://localhost:5432/$databaseName")
    val user = env.getOrElse("LEDGER_DB_USER", defaultUser)
    val password = env.getOrElse("LEDGER_DB_PASSWORD", defaultPassword)
    env.get("LEDGER_DB_SCHEMA") match
      case Some(schema) => dataSource(url, user, password, schema)
      case None         => dataSource(url, user, password)

  val ddl: List[String] = List(
    "CREATE SEQUENCE LEDGER_ID_SEQ",
    """CREATE TABLE ACCOUNT (
         CODE VARCHAR PRIMARY KEY,
         CATEGORY VARCHAR NOT NULL,
         NORMAL_SIDE VARCHAR NOT NULL CHECK (NORMAL_SIDE IN ('DR','CR')),
         UNIT VARCHAR NOT NULL,
         OWNER_TYPE VARCHAR,
         OWNER_ID VARCHAR,
         POSTABLE BOOLEAN NOT NULL,
         SYSTEM_MANAGED BOOLEAN NOT NULL,
         STATUS VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    "CREATE INDEX IX_ACCOUNT_CATEGORY ON ACCOUNT (CATEGORY)",
    "CREATE INDEX IX_ACCOUNT_OWNER ON ACCOUNT (OWNER_TYPE, OWNER_ID)",
    """CREATE TABLE LEDGER_TX (
         ID BIGINT PRIMARY KEY,
         KIND VARCHAR NOT NULL,
         SOURCE_KIND VARCHAR,
         SOURCE_ID VARCHAR,
         USER_UID VARCHAR NOT NULL,
         TARGET_TX_ID BIGINT,
         WITHDRAWAL_ID BIGINT,
         PROPOSAL_ID BIGINT,
         PAYOUT_INTENT_ID BIGINT,
         INCENTIVE_TRACE_ID VARCHAR,
         INCENTIVE_MODULE VARCHAR,
         RAW_INPUT TEXT,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CONSTRAINT CK_CREDIT_HAS_SOURCE CHECK (KIND <> 'IncentiveCredit' OR (SOURCE_KIND IS NOT NULL AND SOURCE_ID IS NOT NULL))
       )""",
    "CREATE UNIQUE INDEX UQ_LEDGER_TX_SOURCE ON LEDGER_TX (SOURCE_KIND, SOURCE_ID)",
    "CREATE INDEX IX_LEDGER_TX_USER ON LEDGER_TX (USER_UID)",
    "CREATE INDEX IX_LEDGER_TX_KIND ON LEDGER_TX (KIND)",
    "CREATE INDEX IX_LEDGER_TX_TARGET ON LEDGER_TX (TARGET_TX_ID)",
    "CREATE INDEX IX_LEDGER_TX_WITHDRAWAL ON LEDGER_TX (WITHDRAWAL_ID)",
    "CREATE INDEX IX_LEDGER_TX_PAYOUT_INTENT ON LEDGER_TX (PAYOUT_INTENT_ID)",
    """CREATE TABLE LEDGER_ENTRY (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         TX_ID BIGINT NOT NULL REFERENCES LEDGER_TX(ID),
         LINE_NO INT NOT NULL,
         ACCOUNT_ID VARCHAR NOT NULL REFERENCES ACCOUNT(CODE),
         DIRECTION VARCHAR NOT NULL CHECK (DIRECTION IN ('DR','CR')),
         AMOUNT BIGINT NOT NULL CHECK (AMOUNT > 0),
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         UNIQUE (TX_ID, LINE_NO)
       )""",
    "CREATE INDEX IX_LEDGER_ENTRY_TX ON LEDGER_ENTRY (TX_ID)",
    "CREATE INDEX IX_LEDGER_ENTRY_ACCOUNT ON LEDGER_ENTRY (ACCOUNT_ID)",
    """CREATE TABLE ACCOUNT_BALANCE (
         ACCOUNT_ID VARCHAR PRIMARY KEY REFERENCES ACCOUNT(CODE),
         BALANCE BIGINT NOT NULL DEFAULT 0,
         UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE OR REPLACE FUNCTION LEDGER_REJECT_MUTATION()
       RETURNS trigger
       LANGUAGE plpgsql
       AS $$
       BEGIN
         RAISE EXCEPTION 'append-only ledger table % rejects %', TG_TABLE_NAME, TG_OP;
       END;
       $$""",
    "CREATE TRIGGER LEDGER_TX_NO_MUTATION BEFORE UPDATE OR DELETE ON LEDGER_TX FOR EACH ROW EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    "CREATE TRIGGER LEDGER_ENTRY_NO_MUTATION BEFORE UPDATE OR DELETE ON LEDGER_ENTRY FOR EACH ROW EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    "CREATE TRIGGER LEDGER_TX_NO_TRUNCATE BEFORE TRUNCATE ON LEDGER_TX FOR EACH STATEMENT EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    "CREATE TRIGGER LEDGER_ENTRY_NO_TRUNCATE BEFORE TRUNCATE ON LEDGER_ENTRY FOR EACH STATEMENT EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    """CREATE OR REPLACE FUNCTION LEDGER_TX_BALANCED_IMPL(v_tx_id BIGINT)
       RETURNS VOID
       LANGUAGE plpgsql
       AS $$
       DECLARE
         v_imbalance BIGINT;
         v_dr_count BIGINT;
         v_cr_count BIGINT;
       BEGIN
         SELECT COALESCE(SUM(CASE WHEN DIRECTION = 'DR' THEN AMOUNT ELSE -AMOUNT END), 0),
                COUNT(*) FILTER (WHERE DIRECTION = 'DR'),
                COUNT(*) FILTER (WHERE DIRECTION = 'CR')
           INTO v_imbalance, v_dr_count, v_cr_count
           FROM LEDGER_ENTRY
          WHERE TX_ID = v_tx_id;
         IF v_dr_count = 0 OR v_cr_count = 0 OR v_imbalance <> 0 THEN
           RAISE EXCEPTION 'ledger tx % is not balanced (dr=% cr=% delta=%)', v_tx_id, v_dr_count, v_cr_count, v_imbalance;
         END IF;
       END;
       $$""",
    """CREATE OR REPLACE FUNCTION LEDGER_TX_BALANCED_FROM_TX()
       RETURNS trigger
       LANGUAGE plpgsql
       AS $$
       BEGIN
         PERFORM LEDGER_TX_BALANCED_IMPL(NEW.ID);
         RETURN NULL;
       END;
       $$""",
    """CREATE OR REPLACE FUNCTION LEDGER_TX_BALANCED_FROM_ENTRY()
       RETURNS trigger
       LANGUAGE plpgsql
       AS $$
       BEGIN
         PERFORM LEDGER_TX_BALANCED_IMPL(NEW.TX_ID);
         RETURN NULL;
       END;
       $$""",
    "CREATE CONSTRAINT TRIGGER LEDGER_TX_BALANCED_ON_HEADER AFTER INSERT ON LEDGER_TX DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION LEDGER_TX_BALANCED_FROM_TX()",
    "CREATE CONSTRAINT TRIGGER LEDGER_TX_BALANCED_ON_ENTRY AFTER INSERT ON LEDGER_ENTRY DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION LEDGER_TX_BALANCED_FROM_ENTRY()",
    """CREATE TABLE WITHDRAWAL (
         ID BIGINT PRIMARY KEY,
         USER_UID VARCHAR NOT NULL,
         AMOUNT BIGINT NOT NULL,
         CLIENT_REQUEST_ID VARCHAR NOT NULL,
         RESERVE_TX_ID BIGINT NOT NULL REFERENCES LEDGER_TX(ID),
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         UNIQUE (USER_UID, CLIENT_REQUEST_ID)
       )""",
    """CREATE TABLE PAYOUT_INTENT (
         ID BIGINT PRIMARY KEY,
         WITHDRAWAL_ID BIGINT NOT NULL UNIQUE REFERENCES WITHDRAWAL(ID),
         USER_UID VARCHAR NOT NULL,
         PROVIDER VARCHAR NOT NULL,
         ROUTE_CODE VARCHAR NOT NULL,
         DESTINATION_ID VARCHAR NOT NULL,
         GROSS_AMOUNT BIGINT NOT NULL,
         QUOTED_PROVIDER_FEE BIGINT NOT NULL,
         EXPECTED_RECIPIENT_NET BIGINT NOT NULL,
         QUOTE_REF VARCHAR,
         PROVIDER_TRANSFER_REF VARCHAR,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CHECK (GROSS_AMOUNT > 0),
         CHECK (QUOTED_PROVIDER_FEE >= 0),
         CHECK (EXPECTED_RECIPIENT_NET = GROSS_AMOUNT - QUOTED_PROVIDER_FEE)
       )""",
    "CREATE INDEX IX_PAYOUT_INTENT_USER ON PAYOUT_INTENT (USER_UID)",
    """CREATE TABLE PAYOUT_RECONCILIATION (
         PAYOUT_INTENT_ID BIGINT PRIMARY KEY REFERENCES PAYOUT_INTENT(ID),
         PROVIDER_EVENT_ID VARCHAR,
         EXPECTED_FEE BIGINT NOT NULL,
         OBSERVED_FEE BIGINT,
         RESULT VARCHAR NOT NULL,
         NOTE TEXT,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE PAYOUT_DISPATCH (
         PAYOUT_INTENT_ID BIGINT PRIMARY KEY REFERENCES PAYOUT_INTENT(ID),
         WITHDRAWAL_ID BIGINT NOT NULL REFERENCES WITHDRAWAL(ID),
         PROVIDER VARCHAR NOT NULL,
         DESTINATION_ID VARCHAR NOT NULL,
         AMOUNT_MINOR BIGINT NOT NULL CHECK (AMOUNT_MINOR > 0),
         CURRENCY VARCHAR NOT NULL,
         IDEMPOTENCY_KEY VARCHAR NOT NULL UNIQUE,
         STATUS VARCHAR NOT NULL CHECK (STATUS IN ('pending','inflight','dispatched','failed')),
         ATTEMPTS INT NOT NULL DEFAULT 0,
         LAST_ERROR TEXT,
         PROVIDER_TRANSFER_REF VARCHAR,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    "CREATE INDEX IX_PAYOUT_DISPATCH_STATUS ON PAYOUT_DISPATCH (STATUS, CREATED_AT)",
    """CREATE TABLE WITHDRAWAL_STATUS_CHANGE (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         WITHDRAWAL_ID BIGINT NOT NULL REFERENCES WITHDRAWAL(ID),
         FROM_STATUS VARCHAR,
         TO_STATUS VARCHAR NOT NULL,
         REASON VARCHAR NOT NULL,
         ACTOR VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    "CREATE INDEX IX_WITHDRAWAL_STATUS_CHANGE_WD ON WITHDRAWAL_STATUS_CHANGE (WITHDRAWAL_ID, ID)",
    """CREATE TABLE WITHDRAWAL_PROVIDER_EVENT (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         PROVIDER VARCHAR NOT NULL,
         EVENT_ID VARCHAR NOT NULL,
         WITHDRAWAL_ID BIGINT NOT NULL REFERENCES WITHDRAWAL(ID),
         PROVIDER_TRANSFER_REF VARCHAR,
         OUTCOME VARCHAR NOT NULL,
         PROVIDER_FEE_DEBITED BIGINT,
         RAW_INPUT TEXT,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         UNIQUE (PROVIDER, EVENT_ID)
       )""",
    "CREATE INDEX IX_WITHDRAWAL_PROVIDER_EVENT_WD ON WITHDRAWAL_PROVIDER_EVENT (WITHDRAWAL_ID, ID)",
    """CREATE TABLE PROPOSAL (
         ID BIGINT PRIMARY KEY,
         KIND VARCHAR NOT NULL,
         USER_UID VARCHAR NOT NULL,
         DEBIT_ACCOUNT VARCHAR NOT NULL,
         CREDIT_ACCOUNT VARCHAR NOT NULL,
         AMOUNT BIGINT NOT NULL,
         REASON VARCHAR NOT NULL,
         PROPOSED_BY VARCHAR NOT NULL,
         TARGET_TX_ID BIGINT,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE PROPOSAL_STATUS_CHANGE (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         PROPOSAL_ID BIGINT NOT NULL REFERENCES PROPOSAL(ID),
         FROM_STATUS VARCHAR,
         TO_STATUS VARCHAR NOT NULL,
         RESULT_TX_ID BIGINT,
         ACTOR VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    "CREATE INDEX IX_PROPOSAL_STATUS_CHANGE_PROP ON PROPOSAL_STATUS_CHANGE (PROPOSAL_ID, ID)",
    """CREATE TABLE OBLIGATION (
         SOURCE_KIND VARCHAR NOT NULL,
         SOURCE_ID VARCHAR NOT NULL,
         USER_UID VARCHAR NOT NULL,
         ESTIMATED_POINTS BIGINT NOT NULL CHECK (ESTIMATED_POINTS >= 0),
         STATUS VARCHAR NOT NULL,
         REALIZED_TX_ID BIGINT,
         PRIMARY KEY (SOURCE_KIND, SOURCE_ID)
       )""",
    """CREATE TABLE RISK_EVENT (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         KIND VARCHAR NOT NULL,
         SUBJECT VARCHAR NOT NULL,
         DETAIL VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE AUDIT_LOG (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         ACTION VARCHAR NOT NULL,
         ACTOR VARCHAR NOT NULL,
         SUBJECT VARCHAR NOT NULL,
         DETAIL VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE SYSTEM_CONFIG_CHANGE (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         CONFIG_KEY VARCHAR NOT NULL,
         CONFIG_VALUE VARCHAR NOT NULL,
         REASON VARCHAR NOT NULL,
         ACTOR VARCHAR NOT NULL,
         PROPOSED_BY VARCHAR,
         APPROVED_BY VARCHAR,
         EFFECTIVE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE SYSTEM_CONFIG_PROPOSAL (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         CONFIG_KEY VARCHAR NOT NULL,
         CONFIG_VALUE VARCHAR NOT NULL,
         REASON VARCHAR NOT NULL,
         STATUS VARCHAR NOT NULL,
         PROPOSED_BY VARCHAR NOT NULL,
         APPROVED_BY VARCHAR,
         REJECTED_BY VARCHAR,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         DECIDED_AT TIMESTAMP
       )""",
    "ALTER TABLE LEDGER_TX ADD CONSTRAINT FK_LEDGER_TX_PAYOUT_INTENT FOREIGN KEY (PAYOUT_INTENT_ID) REFERENCES PAYOUT_INTENT(ID)"
  )

  val seed: List[String] = List(
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:incentive_expense', 'expense', 'DR', 'PTS', 'System', 'incentive', true, true, 'active')",
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:withdrawal_clearing', 'clearing', 'CR', 'PTS', 'System', 'withdrawal_clearing', true, true, 'active')",
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:cash', 'settlement', 'CR', 'PTS', 'System', 'cash', true, true, 'active')",
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:adjustment', 'adjustment', 'DR', 'PTS', 'System', 'adjustment', true, true, 'active')",
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:fee_recovery', 'revenue', 'CR', 'PTS', 'System', 'fee_recovery', true, true, 'active')",
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:provider_payout_fee', 'expense', 'DR', 'PTS', 'System', 'provider_payout_fee', true, true, 'active')",
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:provider_balance:stripe', 'settlement', 'CR', 'PTS', 'Provider', 'stripe', true, true, 'active')",
    "INSERT INTO ACCOUNT (CODE, CATEGORY, NORMAL_SIDE, UNIT, OWNER_TYPE, OWNER_ID, POSTABLE, SYSTEM_MANAGED, STATUS) VALUES ('system:provider_balance:wise', 'settlement', 'CR', 'PTS', 'Provider', 'wise', true, true, 'active')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('payouts_enabled', 'true', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('single_payout_limit_points', '50000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('per_user_day_payout_limit_points', '100000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('per_user_month_payout_limit_points', '500000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('system_day_payout_limit_points', '10000000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('single_ledger_amount_limit_points', '100000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('per_user_day_point_growth_limit_points', '50000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('payout_currency', 'usd', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('payout_points_per_minor_unit', '1', 'seed', 'system', 'system')"
  )

  def initSchema(c: Connection): Unit =
    (ddl ++ seed).foreach { sql =>
      val st = c.createStatement()
      try st.execute(sql)
      finally st.close()
    }
