package io.linewise.ledger

import java.sql.Connection
import javax.sql.DataSource

import com.zaxxer.hikari.{HikariConfig, HikariDataSource}
import org.postgresql.ds.PGSimpleDataSource

/* =============================================================================
 * SCHEMA + persistence support for the ledger microservice. The production store is
 * PostgreSQL. Tests use the same DDL against an isolated PostgreSQL schema, not H2
 * compatibility mode, so trigger syntax, identity columns, intervals, and TEXT fields
 * are all exercised on the target database.
 * ========================================================================== */
object Jdbc:

  private val defaultUser = "postgres"
  private val defaultPassword = "postgres"
  private val schemaPattern = "[A-Za-z_][A-Za-z0-9_]*".r

  private def pg(url: String, user: String, password: String): PGSimpleDataSource =
    val ds = PGSimpleDataSource()
    ds.setURL(url)
    ds.setUser(user)
    ds.setPassword(password)
    ds

  private def requireSafeSchema(schema: String): Unit =
    require(schemaPattern.matches(schema), s"unsafe PostgreSQL schema name: $schema")

  // Connection pool. PGSimpleDataSource opens a fresh TCP + auth round-trip on every
  // getConnection, and one endpoint call opens several connections, so production must
  // pool. minimumIdle=0 keeps the many short-lived per-schema pools the test harness
  // creates from each pinning an idle connection. The pool is a HikariDataSource, so the
  // owner (server / test harness) can `close()` it to release connections and threads.
  private def pool(url: String, user: String, password: String, schema: Option[String]): HikariDataSource =
    val cfg = HikariConfig()
    cfg.setJdbcUrl(url)
    cfg.setUsername(user)
    cfg.setPassword(password)
    cfg.setMaximumPoolSize(sys.env.get("LEDGER_DB_POOL_SIZE").flatMap(_.toIntOption).getOrElse(8))
    cfg.setMinimumIdle(0)
    schema.foreach(s => cfg.setPoolName(s"ledger-$s"))
    schema.foreach(cfg.setSchema)
    HikariDataSource(cfg)

  def dataSource(jdbcUrl: String, user: String, password: String): DataSource =
    pool(jdbcUrl, user, password, None)

  def dataSource(jdbcUrl: String, user: String, password: String, schema: String): DataSource =
    requireSafeSchema(schema)
    val admin = pg(jdbcUrl, user, password)
    val c0 = admin.getConnection()
    try
      val st = c0.createStatement()
      try st.execute(s"CREATE SCHEMA IF NOT EXISTS $schema")
      finally st.close()
    finally c0.close()
    pool(jdbcUrl, user, password, Some(schema))

  def dataSource(databaseName: String): DataSource =
    val env = sys.env
    val url = env.getOrElse("LEDGER_JDBC_URL", s"jdbc:postgresql://localhost:5432/$databaseName")
    val user = env.getOrElse("LEDGER_DB_USER", defaultUser)
    val password = env.getOrElse("LEDGER_DB_PASSWORD", defaultPassword)
    env.get("LEDGER_DB_SCHEMA") match
      case Some(schema) => dataSource(url, user, password, schema)
      case None         => dataSource(url, user, password)

  val ddl: List[String] = List(
    // One shared sequence supplies every application-assigned id (LEDGER_TX / WITHDRAWAL /
    // PROPOSAL). A DB sequence is monotone across process restarts, so ids never collide
    // with already-persisted rows the way a process-local counter would.
    "CREATE SEQUENCE LEDGER_ID_SEQ",
    """CREATE TABLE LEDGER_TX (
         ID BIGINT PRIMARY KEY,
         KIND VARCHAR NOT NULL,
         SOURCE_KIND VARCHAR,
         SOURCE_ID VARCHAR,
         USER_UID VARCHAR NOT NULL,
         TARGET_TX_ID BIGINT,
         WITHDRAWAL_ID BIGINT,
         PROPOSAL_ID BIGINT,
         INCENTIVE_TRACE_ID VARCHAR,
         INCENTIVE_MODULE VARCHAR,
         RAW_INPUT TEXT,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CONSTRAINT CK_CREDIT_HAS_SOURCE CHECK (KIND <> 'IncentiveCredit' OR (SOURCE_KIND IS NOT NULL AND SOURCE_ID IS NOT NULL))
       )""",
    "CREATE UNIQUE INDEX UQ_LEDGER_TX_SOURCE ON LEDGER_TX (SOURCE_KIND, SOURCE_ID)",
    "CREATE INDEX IX_LEDGER_TX_USER ON LEDGER_TX (USER_UID)",
    "CREATE INDEX IX_LEDGER_TX_KIND ON LEDGER_TX (KIND)",
    "CREATE INDEX IX_LEDGER_TX_TARGET ON LEDGER_TX (TARGET_TX_ID)",
    """CREATE TABLE LEDGER_ENTRY (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         TX_ID BIGINT NOT NULL REFERENCES LEDGER_TX(ID),
         ACCOUNT_ID VARCHAR NOT NULL,
         DIRECTION VARCHAR NOT NULL CHECK (DIRECTION IN ('DR','CR')),
         AMOUNT BIGINT NOT NULL CHECK (AMOUNT > 0),
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    "CREATE INDEX IX_LEDGER_ENTRY_TX ON LEDGER_ENTRY (TX_ID)",
    "CREATE INDEX IX_LEDGER_ENTRY_ACCOUNT ON LEDGER_ENTRY (ACCOUNT_ID)",
    // ACCOUNT_BALANCE is the intentionally-MUTABLE materialized view of the ledger: every
    // posting UPDATEs it, and `balanceDrifts` + the account_balance_matches_replay invariant
    // reconcile it against replaying LEDGER_ENTRY. It deliberately has no append-only guard.
    // NB: no `user balance >= 0` CHECK. The verified ledger repository permits ANY balanced
    // posting regardless of resulting sign — balance sufficiency is a shell-layer policy
    // (lockUserBalance + the sufficiency check), not a repository invariant. A DB CHECK would
    // make the JDBC realization reject overdraws the InMem oracle accepts, so the differential
    // drift gate would (correctly) flag the realization as unfaithful to the proven model.
    """CREATE TABLE ACCOUNT_BALANCE (
         ACCOUNT_ID VARCHAR PRIMARY KEY,
         BALANCE BIGINT NOT NULL DEFAULT 0,
         UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE OR REPLACE FUNCTION LEDGER_REJECT_MUTATION()
       RETURNS trigger
       LANGUAGE plpgsql
       AS $$
       BEGIN
         RAISE EXCEPTION 'append-only ledger table % rejects %', TG_TABLE_NAME, TG_OP;
       END;
       $$""",
    "CREATE TRIGGER LEDGER_TX_NO_MUTATION BEFORE UPDATE OR DELETE ON LEDGER_TX FOR EACH ROW EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    "CREATE TRIGGER LEDGER_ENTRY_NO_MUTATION BEFORE UPDATE OR DELETE ON LEDGER_ENTRY FOR EACH ROW EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    // Row-level triggers do not fire on TRUNCATE, so append-only also needs statement-level
    // BEFORE TRUNCATE triggers, or the whole table could be wiped past the guard.
    "CREATE TRIGGER LEDGER_TX_NO_TRUNCATE BEFORE TRUNCATE ON LEDGER_TX FOR EACH STATEMENT EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    "CREATE TRIGGER LEDGER_ENTRY_NO_TRUNCATE BEFORE TRUNCATE ON LEDGER_ENTRY FOR EACH STATEMENT EXECUTE FUNCTION LEDGER_REJECT_MUTATION()",
    // Double-entry conservation, enforced at the DB: at COMMIT, the signed entry sum (DR +, CR -)
    // of every tx must be zero. A DEFERRABLE INITIALLY DEFERRED constraint trigger is required so
    // the check runs once both legs are present, not after the first leg is inserted.
    """CREATE OR REPLACE FUNCTION LEDGER_TX_BALANCED()
       RETURNS trigger
       LANGUAGE plpgsql
       AS $$
       DECLARE imbalance BIGINT;
       BEGIN
         SELECT COALESCE(SUM(CASE WHEN DIRECTION = 'DR' THEN AMOUNT ELSE -AMOUNT END), 0)
           INTO imbalance FROM LEDGER_ENTRY WHERE TX_ID = NEW.TX_ID;
         IF imbalance <> 0 THEN
           RAISE EXCEPTION 'ledger tx % is not balanced (DR-CR = %)', NEW.TX_ID, imbalance;
         END IF;
         RETURN NULL;
       END;
       $$""",
    "CREATE CONSTRAINT TRIGGER LEDGER_ENTRY_BALANCED AFTER INSERT ON LEDGER_ENTRY DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION LEDGER_TX_BALANCED()",

    """CREATE TABLE WITHDRAWAL (
         ID BIGINT PRIMARY KEY,
         USER_UID VARCHAR NOT NULL,
         AMOUNT BIGINT NOT NULL,
         CLIENT_REQUEST_ID VARCHAR NOT NULL,
         RESERVE_TX_ID BIGINT NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         UNIQUE (USER_UID, CLIENT_REQUEST_ID)
       )""",
    """CREATE TABLE WITHDRAWAL_STATUS_CHANGE (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         WITHDRAWAL_ID BIGINT NOT NULL REFERENCES WITHDRAWAL(ID),
         FROM_STATUS VARCHAR,
         TO_STATUS VARCHAR NOT NULL,
         REASON VARCHAR NOT NULL,
         ACTOR VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    "CREATE INDEX IX_WITHDRAWAL_STATUS_CHANGE_WD ON WITHDRAWAL_STATUS_CHANGE (WITHDRAWAL_ID, ID)",
    """CREATE TABLE WITHDRAWAL_PROVIDER_EVENT (
         EVENT_ID VARCHAR PRIMARY KEY,
         WITHDRAWAL_ID BIGINT NOT NULL,
         OUTCOME VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",

    """CREATE TABLE PROPOSAL (
         ID BIGINT PRIMARY KEY,
         KIND VARCHAR NOT NULL,
         USER_UID VARCHAR NOT NULL,
         DEBIT_ACCOUNT VARCHAR NOT NULL,
         CREDIT_ACCOUNT VARCHAR NOT NULL,
         AMOUNT BIGINT NOT NULL,
         REASON VARCHAR NOT NULL,
         PROPOSED_BY VARCHAR NOT NULL,
         TARGET_TX_ID BIGINT,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE PROPOSAL_STATUS_CHANGE (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         PROPOSAL_ID BIGINT NOT NULL REFERENCES PROPOSAL(ID),
         FROM_STATUS VARCHAR,
         TO_STATUS VARCHAR NOT NULL,
         RESULT_TX_ID BIGINT,
         ACTOR VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    "CREATE INDEX IX_PROPOSAL_STATUS_CHANGE_PROP ON PROPOSAL_STATUS_CHANGE (PROPOSAL_ID, ID)",

    """CREATE TABLE OBLIGATION (
         SOURCE_KIND VARCHAR NOT NULL,
         SOURCE_ID VARCHAR NOT NULL,
         USER_UID VARCHAR NOT NULL,
         ESTIMATED_POINTS BIGINT NOT NULL,
         STATUS VARCHAR NOT NULL,
         REALIZED_TX_ID BIGINT,
         PRIMARY KEY (SOURCE_KIND, SOURCE_ID)
       )""",

    """CREATE TABLE RISK_EVENT (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         KIND VARCHAR NOT NULL,
         SUBJECT VARCHAR NOT NULL,
         DETAIL VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE AUDIT_LOG (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         ACTION VARCHAR NOT NULL,
         ACTOR VARCHAR NOT NULL,
         SUBJECT VARCHAR NOT NULL,
         DETAIL VARCHAR NOT NULL,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE SYSTEM_CONFIG_CHANGE (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         CONFIG_KEY VARCHAR NOT NULL,
         CONFIG_VALUE VARCHAR NOT NULL,
         REASON VARCHAR NOT NULL,
         ACTOR VARCHAR NOT NULL,
         PROPOSED_BY VARCHAR,
         APPROVED_BY VARCHAR,
         EFFECTIVE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
       )""",
    """CREATE TABLE SYSTEM_CONFIG_PROPOSAL (
         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         CONFIG_KEY VARCHAR NOT NULL,
         CONFIG_VALUE VARCHAR NOT NULL,
         REASON VARCHAR NOT NULL,
         STATUS VARCHAR NOT NULL,
         PROPOSED_BY VARCHAR NOT NULL,
         APPROVED_BY VARCHAR,
         REJECTED_BY VARCHAR,
         CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         DECIDED_AT TIMESTAMP
       )"""
  )

  val seed: List[String] = List(
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('payouts_enabled', 'true', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('single_payout_limit_points', '50000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('per_user_day_payout_limit_points', '100000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('per_user_month_payout_limit_points', '500000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('system_day_payout_limit_points', '10000000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('single_ledger_amount_limit_points', '100000', 'seed', 'system', 'system')",
    "INSERT INTO SYSTEM_CONFIG_CHANGE (CONFIG_KEY, CONFIG_VALUE, REASON, ACTOR, APPROVED_BY) VALUES ('per_user_day_point_growth_limit_points', '50000', 'seed', 'system', 'system')"
    // No stripe_webhook_secret is seeded: production sets it from LEDGER_WEBHOOK_SECRET at
    // startup; absent that, webhookSignature falls back to a per-process random secret
    // (never a shipped constant). See LedgerStore.webhookSignature / LedgerServer.
  )

  def initSchema(c: Connection): Unit =
    (ddl ++ seed).foreach { sql =>
      val st = c.createStatement()
      try st.execute(sql)
      finally st.close()
    }
