BEGIN;

DELETE FROM ACCOUNT_BALANCE;

INSERT INTO ACCOUNT_BALANCE (ACCOUNT_ID, BALANCE, UPDATED_AT)
SELECT
  ACCOUNT_ID,
  SUM(CASE
    WHEN DIRECTION = CASE
      WHEN ACCOUNT_ID LIKE 'user:%' OR ACCOUNT_ID = 'system:withdrawal_clearing' THEN 'CR'
      ELSE 'DR'
    END THEN AMOUNT ELSE -AMOUNT END) AS BALANCE,
  CURRENT_TIMESTAMP
FROM LEDGER_ENTRY
GROUP BY ACCOUNT_ID;

COMMIT;
