BEGIN;

DELETE FROM ACCOUNT_BALANCE;

INSERT INTO ACCOUNT_BALANCE (ACCOUNT_ID, BALANCE, UPDATED_AT)
SELECT
  e.ACCOUNT_ID,
  SUM(CASE WHEN e.DIRECTION = a.NORMAL_SIDE THEN e.AMOUNT ELSE -e.AMOUNT END) AS BALANCE,
  CURRENT_TIMESTAMP
FROM LEDGER_ENTRY e
JOIN ACCOUNT a ON a.CODE = e.ACCOUNT_ID
GROUP BY e.ACCOUNT_ID;

COMMIT;
